# Name of your application. Used to uniquely configure containers.
service: app_flow_starter-production

# Name of the container image.
image: laterolabs/app_flow_starter_production

# Deploy to these servers.
servers:
  web:
    hosts: &shared_hosts
      - 5.78.98.232
    proxy:
      ssl: true
      hosts:
        - app_flow_starter.laterolabs.com
  rpc:
    hosts: *shared_hosts
    options:
      network-alias: app_flow_starter-production-rpc

# Use accessory services (secrets come from .kamal/secrets.production).
# DATABASE_URL=postgres://app_flow_starter-production-user:<POSTGRES_PASSWORD>@app_flow_starter-production-postgres:5432/app_flow_starter-production
# REDIS_URL=redis://:<REDIS_PASSWORD>@app_flow_starter-production-redis:6379/0
accessories:
  postgres:
    service: app_flow_starter-production-postgres
    hosts: *shared_hosts
    env:
      clear:
        POSTGRES_USER: app_flow_starter-production-user
        POSTGRES_DB: app_flow_starter-production
    directories:
      - /home/deployer/app_flow_starter-production-postgres:/var/lib/postgresql
  redis:
    service: app_flow_starter-production-redis
    hosts: *shared_hosts
  anycable_go:
    service: app_flow_starter-production-anycable-go
    hosts: *shared_hosts
    env:
      clear:
        ANYCABLE_RPC_HOST: app_flow_starter-production-rpc:50051
      secret:
        - ANYCABLE_REDIS_URL
    proxy:
      ssl: true
      host: app_flow_starter-websockets.laterolabs.com
