# Name of your application. Used to uniquely configure containers.
service: day_planner-production

# Name of the container image.
image: laterolabs/day_planner_production

# Deploy to these servers.
servers:
  web:
    hosts: &shared_hosts
      - 5.78.98.232
    proxy:
      ssl: true
      hosts:
        - day_planner.laterolabs.com
  rpc:
    hosts: *shared_hosts
    options:
      network-alias: day_planner-production-rpc

# Use accessory services (secrets come from .kamal/secrets.production).
# DATABASE_URL=postgres://day_planner-production-user:<POSTGRES_PASSWORD>@day_planner-production-postgres:5432/day_planner-production
# REDIS_URL=redis://:<REDIS_PASSWORD>@day_planner-production-redis:6379/0
accessories:
  postgres:
    service: day_planner-production-postgres
    hosts: *shared_hosts
    env:
      clear:
        POSTGRES_USER: day_planner-production-user
        POSTGRES_DB: day_planner-production
    directories:
      - /home/deployer/day_planner-production-postgres:/var/lib/postgresql
  redis:
    service: day_planner-production-redis
    hosts: *shared_hosts
  anycable_go:
    service: day_planner-production-anycable-go
    hosts: *shared_hosts
    env:
      clear:
        ANYCABLE_RPC_HOST: day_planner-production-rpc:50051
      secret:
        - ANYCABLE_REDIS_URL
    proxy:
      ssl: true
      host: day_planner-websockets.laterolabs.com
